name: Deploy to GitHub Pages

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ui-prototyping
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack and set Yarn version
        run: |
          corepack enable
          corepack prepare yarn@4.9.1 --activate

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build project
        run: yarn build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ui-prototyping/dist
          publish_branch: gh-pages
          force_orphan: true
